version: '3'
services:
  web:
    build: ./app
    command: gunicorn --workers=4 app:app --bind 0.0.0.0:5000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 5000:5000
  vue-ui:
    build: ./client
    command: npm run dev
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - "8081:8081"
